### ISSUE TITLE
微博情感分析的03代码和05代码

### ISSUE THREAD

**Issue by wslcug** [dengxiuqi/WeiboSentiment#2]
03代码_X = np.concatenate(X_test + [np.zeros_like(X_test[0])] * (batch_size - len(X_test)))和05代码中 _X = np.concatenate(X_test + [np.zeros_like(X_test[0])] * (batch_size - len(X_test))) _L = np.array(test_length + [1] * (batch_size - len(test_length)))运行后对测试集的预测会报数据格式的错误，想请教一下老哥！

**Comment by dengxiuqi** [comment]
我这里无法复现这个错误。不过我已经对工程进行了重构，希望可以帮到你

**Comment by wslcug** [comment]
谢谢老哥您的答复，能问下您有尝试做情感多分类嘛，或者有情感多分类的一些案例能参考一下的。万分感激热心的您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dengxiuqi/WeiboSentiment"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 下午2:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dengxiuqi/WeiboSentiment] 微博情感分析的03代码和05代码 (#2)





 
Closed #2.

**Comment by dengxiuqi** [comment]
做过，不过是读书期间跟企业合作的项目，不能公开。跟二分类大同小异吧，另外会有正面和中性情感经常分类错误的情况发生
