### ISSUE TITLE
LSTM代码无法使用

### ISSUE THREAD

**Issue by Dicer-Zz** [dengxiuqi/WeiboSentiment#3]
由于tensorflow改版，LSTM的代码已经不能再最新版上使用了，方便告知一下这份代码的tensorflow版本吗？

**Comment by dengxiuqi** [comment]
我换电脑后也跑不起来了...更新了一下，换成pytorch了，并新增了requirements.txt

**Comment by Dicer-Zz** [comment]
真不戳，感谢！
